name: Sky
author: LimeGlass
description: A Skyblock Skript Addon, supports uSkyblock, ASkyblock and BentoBox.
version: @version@
main: me.limeglass.sky.Sky
softdepend: [uSkyblock, ASkyblock, SkyBlock, BentoBox]
